# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='empty', max_length=2000),
            preserve_default=False,
        ),
    ]
