# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20171112_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default="somebody didn't think about notes earlier on", max_length=255),
            preserve_default=False,
        ),
    ]
